server:
  port: 5050

spring:
  application:
    name: graphql-api-gateway
  config:
    import: 'optional:configserver:'
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true